/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dataservices.dao.CompraDAO;
import dataservices.dao.FornecedorDAO;
import dataservices.dao.FuncionarioDAO;
import domain.Cliente;
import domain.Compra;
import domain.Fornecedor;
import domain.Funcionario;
import java.time.LocalDate;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import resources.CompraTableModel;

/**
 *
 * @author felipe_baumgartel
 */
public class CadCompra extends javax.swing.JFrame {

    CompraDAO dao = new CompraDAO();
    
    public CadCompra() {
        initComponents();
        desabilitaComponetes();
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
        atualizarTabela();
        carregarFornecedor();
        carregarFuncionario();
        cbFornecedor.setSelectedIndex(-1);
        cbFunc.setSelectedIndex(-1);
        txCd.setEnabled(false);
        this.setTitle("Cadstro de Compra");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bt_Cancelar = new javax.swing.JButton();
        bt_Add = new javax.swing.JButton();
        bt_Finalizar = new javax.swing.JButton();
        btFechar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cbFornecedor = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cbFunc = new javax.swing.JComboBox();
        txValor = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txData = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        txCd = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 204));

        bt_Cancelar.setBackground(new java.awt.Color(102, 102, 255));
        bt_Cancelar.setText("Cancelar Último Produto");
        jPanel1.add(bt_Cancelar);

        bt_Add.setBackground(new java.awt.Color(102, 102, 255));
        bt_Add.setText("Adicionar Produto");
        bt_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_AddActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Add);

        bt_Finalizar.setBackground(new java.awt.Color(102, 102, 255));
        bt_Finalizar.setText("Finalizar Compra");
        bt_Finalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_FinalizarActionPerformed(evt);
            }
        });
        jPanel1.add(bt_Finalizar);

        btFechar.setBackground(new java.awt.Color(102, 102, 255));
        btFechar.setText("Fechar");
        btFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFecharActionPerformed(evt);
            }
        });
        jPanel1.add(btFechar);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setBackground(new java.awt.Color(102, 102, 255));

        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel4.setText("Fornecedor");

        jLabel3.setText("Funcionário");

        cbFunc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbFuncActionPerformed(evt);
            }
        });

        jLabel1.setText("Valor");

        jLabel2.setText("Data");

        try {
            txData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("####-##-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel5.setText("Codigo");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txValor)
                    .addComponent(cbFunc, 0, 150, Short.MAX_VALUE)
                    .addComponent(cbFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txData)
                    .addComponent(txCd))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 267, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txCd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(cbFunc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbFuncActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbFuncActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbFuncActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() > 1) {

            Compra a = ctm.getValueAT(jTable1.getSelectedRow());
            recuperaCompra(a);
        }
    }//GEN-LAST:event_jTable1MouseClicked

    private void bt_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_AddActionPerformed
        if(dao2.list(daoPed.idPedido()).isEmpty()){
            dao2.Save (cadastrar());
            dao2.Save1(adicionar());
        }else{
            dao2.Save1(adicionar());
        }
        atualizarProdutos();
    }//GEN-LAST:event_bt_AddActionPerformed

    private void bt_FinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt_FinalizarActionPerformed
        dao2.Save(cadastrar());
        JOptionPane.showMessageDialog(null, "Valor Total = "+dao2.total);
    }//GEN-LAST:event_bt_FinalizarActionPerformed

    private void btFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFecharActionPerformed
        this.dispose();
    }//GEN-LAST:event_btFecharActionPerformed

    private void carregarFuncionario() {
        for (Funcionario Funcionario : FuncionarioDAO.list()) {
            cbFunc.addItem(Funcionario.getNm_pessoas());
        }
    }
    private void carregarFornecedor() {
        for (Fornecedor Fornecedor : FornecedorDAO.list()) {
            cbFornecedor.addItem(Fornecedor.getNm_fornecedor());
        }
    }
     

    private Compra criarCompra() {
        double valor = Double.parseDouble(txValor.getText());
        LocalDate data = LocalDate.parse(txData.getText());
        Fornecedor Fornecedor = (Fornecedor) cbFornecedor.getSelectedItem();
        Funcionario Funcionario = (Funcionario) cbFunc.getSelectedItem();

        return new Compra(valor, data, Funcionario, Fornecedor);
    }

    private void recuperaCompra(Compra a) {
        HabilitaComponetes();
        txValor.setText(String.valueOf(a.getVl_compra()));
        txData.setText(String.valueOf(a.getDt_compra()));
        cbFornecedor.setSelectedItem(a.getFornecedor());
        cbFunc.setSelectedItem(a.getFuncionario());
        
    }

    private void limpaCampoDetexto() {
        txValor.setText("");
        txData.setText("");
        txCd.setText("");
        cbFornecedor.setSelectedItem(0);
        cbFunc.setSelectedItem(0);
    }

    private void HabilitaComponetes() {
        txValor.setEnabled(true);
        txData.setEnabled(true);
        cbFornecedor.setEnabled(true);
        cbFunc.setEnabled(true);

        btNovo.setEnabled(false);
        btCancelar.setEnabled(true);
        btSalvar.setEnabled(true);
    }

    private void desabilitaComponetes() {
        txValor.setEnabled(false);
        txData.setEnabled(false);
        cbFornecedor.setEnabled(false);
        cbFunc.setEnabled(false);

        btNovo.setEnabled(true);
        btCancelar.setEnabled(false);
        btSalvar.setEnabled(false);
    }

    private TableModel carregarTabela() {
        List<Compra> lista = dao.list();
        ctm = new CompraTableModel(lista);
        return ctm;
    }

    private void atualizarTabela() {
        jTable1.setModel(carregarTabela());
    }

    private CompraTableModel ctm;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFechar;
    private javax.swing.JButton bt_Add;
    private javax.swing.JButton bt_Cancelar;
    private javax.swing.JButton bt_Finalizar;
    private javax.swing.JComboBox cbFornecedor;
    private javax.swing.JComboBox cbFunc;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txCd;
    private javax.swing.JFormattedTextField txData;
    private javax.swing.JTextField txValor;
    // End of variables declaration//GEN-END:variables
}
